# Generated by Django 4.2.5 on 2024-04-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.RemoveField(
            model_name='hod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='hod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
