# Generated by Django 4.2.5 on 2024-04-09 15:49

from django.db import migrations, models
import usermodule.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_alter_courses_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='course_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.FileField(blank=True, upload_to=usermodule.models.Staff.wrapper),
        ),
    ]
