# Generated by Django 4.2.5 on 2024-04-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0004_hod_email_hod_email_varified_hod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='email_varified',
            field=models.BooleanField(default=False),
        ),
    ]
