# Generated by Django 4.2.5 on 2024-04-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0005_staff_email_varified_student_email_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.hod'),
        ),
        migrations.AddField(
            model_name='student',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.hod'),
        ),
    ]
