# Generated by Django 4.2.5 on 2024-05-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0007_rename_email_varified_hod_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod',
            old_name='verified',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='staff',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
