# Generated by Django 4.2.5 on 2024-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0008_rename_verified_hod_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
