# Generated by Django 4.2.5 on 2024-05-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0009_alter_hod_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.staff')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.student')),
            ],
        ),
        migrations.CreateModel(
            name='ApproveStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_hod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.hod')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ApproveHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_hod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver_hod', to='usermodule.hod')),
                ('hod', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_hod', to='usermodule.hod')),
            ],
        ),
    ]
