# Generated by Django 4.2.5 on 2024-04-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermodule', '0001_initial'),
        ('datamodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectwithstaff',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.staff'),
        ),
        migrations.AddField(
            model_name='subjectwithstaff',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datamodule.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermodule.courses'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodule.attendance'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datamodule.subjectwithstaff'),
        ),
    ]
