# Generated by Django 4.2.5 on 2024-04-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0007_rename_email_varified_hod_verified_and_more'),
        ('datamodule', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermodule.semester'),
        ),
    ]
