# Generated by Django 4.2.5 on 2024-04-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0007_rename_email_varified_hod_verified_and_more'),
        ('datamodule', '0003_subject_semester_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.courses')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usermodule.semester')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datamodule.timeslot')),
            ],
        ),
    ]
