# Generated by Django 4.2.5 on 2024-04-23 16:53

from django.db import migrations, models
import django.db.models.deletion

def create_timeslots(apps, schema_editor):
    TimeSlot = apps.get_model('datamodule', 'TimeSlot')
    
    # Create some default time slots
    TimeSlot.objects.create(start_time='10:30:00', end_time='11:30:00')
    TimeSlot.objects.create(start_time='11:30:00', end_time='12:30:00')
    TimeSlot.objects.create(start_time='12:30:00', end_time='13:30:00')
    TimeSlot.objects.create(start_time='13:50:00', end_time='14:50:00')
    TimeSlot.objects.create(start_time='14:50:00', end_time='15:50:00')
    TimeSlot.objects.create(start_time='15:50:00', end_time='16:50:00')

def create_routines(apps, schema_editor):
    Routine = apps.get_model('datamodule', 'Routine')
    Course = apps.get_model('usermodule', 'Courses')
    Semester = apps.get_model('usermodule', 'Semester')
    TimeSlot = apps.get_model('datamodule', 'TimeSlot')

    courses = Course.objects.all()
    semesters = Semester.objects.all()
    timeslots = TimeSlot.objects.all()

    for course in courses:
        for semester in semesters:
            for day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']:
                if day != "Saturday":
                    for time in timeslots:
                    # Randomly select a timeslot
                        Routine.objects.create(course=course, semester=semester, day=day, timeslot=time)
                else:
                    
                    time = TimeSlot.objects.filter(start_time='10:30:00', end_time='11:30:00').first()
                    Routine.objects.create(course=course, semester=semester, day=day, timeslot=time)
                    time = TimeSlot.objects.filter(start_time='11:30:00', end_time='12:30:00').first()
                    Routine.objects.create(course=course, semester=semester, day=day, timeslot=time)
                    time = TimeSlot.objects.filter(start_time='12:30:00', end_time='13:30:00').first()
                    Routine.objects.create(course=course, semester=semester, day=day, timeslot=time)


class Migration(migrations.Migration):

    dependencies = [
        ('datamodule', '0004_timeslot_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datamodule.subject'),
        ),
        migrations.RunPython(create_timeslots),
        migrations.RunPython(create_routines),
    ]
