# Generated by Django 4.2.5 on 2024-05-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodule', '0005_routine_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datamodule.subjectwithstaff'),
        ),
    ]
